#!/bin/bash

# GPU_INFO="--partition viscam --account viscam --gpu_type 3090 --cpus_per_task 8 --num_gpus 1 --mem 100G"
GPU_INFO="--partition viscam --account viscam --gpu_type a6000 --cpus_per_task 8 --num_gpus 1 --mem 24G"
# GPU_INFO="--partition viscam --account viscam --gpu_type titanrtx --cpus_per_task 8 --num_gpus 1 --mem 64G"

# GPU_INFO="--partition svl --account viscam --gpu_type titanrtx --cpus_per_task 8 --num_gpus 1 --mem 64G"

# EXTRA_GPU_INFO="exclude=viscam1,viscam5,viscam7,svl[1-6],svl[8-10]"


python -m tu.sbatch.sbatch_sweep --time 96:00:00 \
--proj_dir /viscam/projects/image2Blender/differentiable_engine/LocInv --conda_env dpl \
--job "07-28-locinv-chair" --command "python _2_DDIM_inv.py --input_image images/rendered_chair.jpg --results_folder ./output --num_ddim_steps 1 && python _3_dpl_seg_inv.py --input_image images/rendered_chair.jpg --results_folder output/rendered_chair --max_iter_to_alter 0 --initializer_token chair --placeholder_token  '<chair>'  --lam_cos 1.0 --lam_iou 1.0 --lam_kl 1.0 --lam_adj 0.0 --smooth_op --softmax_op --seg_dirs seg_dirs/rendered_chair --target_image images/rendered_chair.jpg --num_ddim_steps 1 --exp_name one_word" $GPU_INFO

python _3_dpl_seg_inv.py --input_image images/rendered_chair.jpg --results_folder output/rendered_chair --max_iter_to_alter 0 --initializer_token chair --placeholder_token  '<chair>'  --lam_cos 1.0 --lam_iou 1.0 --lam_kl 1.0 --lam_adj 0.0 --smooth_op --softmax_op --seg_dirs seg_dirs/rendered_chair --target_image images/rendered_chair.jpg --num_ddim_steps 1 --exp_name one_word --attn_inner_steps 100 && python _3_dpl_seg_inv.py --input_image images/rendered_chair.jpg --results_folder output/rendered_chair --max_iter_to_alter 0 --initializer_token one two three four five six --placeholder_token  '<one>' '<two>' '<three>' '<four>' '<five>' '<six>'  --lam_cos 1.0 --lam_iou 1.0 --lam_kl 1.0 --lam_adj 0.0 --smooth_op --softmax_op --seg_dirs seg_dirs/rendered_chair --target_image images/rendered_chair.jpg --num_ddim_steps 1 --prompt_file chair_numbers.txt --exp_name six_words --attn_inner_steps 100

python _2_DDIM_inv.py --input_image images/rendered_chair.jpg --results_folder ./output --num_ddim_steps 100 && python _3_dpl_seg_inv.py --input_image images/rendered_chair.jpg --results_folder output/rendered_chair --max_iter_to_alter 0 --initializer_token chair --placeholder_token  '<chair>'  --lam_cos 2.0 --lam_iou 2.0 --lam_kl 2.0 --lam_adj 0.0 --smooth_op --softmax_op --seg_dirs seg_dirs/rendered_chair --target_image images/chair_green.jpg --num_ddim_steps 100 --exp_name one_word_green_latents --attn_inner_steps 50 --null_inner_steps 100

python _2_DDIM_inv.py --input_image images/chair1.jpg --results_folder ./output/rev_brown_chair && python _3_dpl_seg_inv.py --input_image images/chair1.jpg --results_folder output/rev_brown_chair --initializer_token chair --placeholder_token  '<chair>' --smooth_op --softmax_op --seg_dirs seg_dirs/rendered_chair --exp_name rev_brown_chair 

 --lam_cos 0.0 --lam_iou 0.0 --lam_kl 0.0 --lam_adj 0.0

 python _2_DDIM_inv.py --input_image images/chair1.jpg --results_folder ./output/rev_catdog_brown_chair && python _3_dpl_seg_inv.py --input_image images/chair1.jpg --results_folder output/rev_catdog_brown_chair --initializer_token cat dog --placeholder_token  '<cat-toy>' '<dog-toy>' --smooth_op --softmax_op --seg_dirs seg_dirs/catdog --exp_name rev_catdog_brown_chair 

  python _2_DDIM_inv.py --input_image images/chair1.jpg --results_folder ./output/rev_catdog_brown_chair_no_threshold && python _3_dpl_seg_inv.py --input_image images/chair1.jpg --results_folder output/rev_catdog_brown_chair_no_threshold --initializer_token cat dog --placeholder_token  '<cat-toy>' '<dog-toy>' --smooth_op --softmax_op --seg_dirs seg_dirs/catdog --exp_name rev_catdog_brown_chair_no_threshold --beta_cos 0.0 --beta_iou 0.0 --beta_kl 0.0 --beta_sim 0.0 --beta_adj 0.0
  
  python _2_DDIM_inv.py --input_image images/chair1.jpg --results_folder ./output/rev_brown_chair_yes_threshold && python _3_dpl_seg_inv.py --input_image images/chair1.jpg --results_folder output/rev_brown_chair_yes_threshold --initializer_token chair --placeholder_token  '<chair>' --smooth_op --softmax_op --seg_dirs seg_dirs/rendered_chair --exp_name rev_brown_chair_yes_threshold --beta_cos 0.2 --beta_iou 0.2 --beta_kl 0.2 --beta_sim 0.2 --beta_adj 0.0



  python _3_dpl_seg_inv.py --input_image images/chair1.jpg --results_folder output/rev_brown_chair_yes_threshold --initializer_token chair --placeholder_token  '<chair>' --smooth_op --softmax_op --seg_dirs seg_dirs/rendered_chair --exp_name rev_brown_chair_yes_threshold --beta_cos 0.3 --beta_iou 0.3 && python _3_dpl_seg_inv.py --input_image images/chair1.jpg --results_folder output/rev_brown_chair_yes_threshold --initializer_token chair --placeholder_token  '<chair>' --smooth_op --softmax_op --seg_dirs seg_dirs/rendered_chair --exp_name rev_brown_chair_yes_threshold --beta_cos 0.4 --beta_iou 0.4

    python _2_DDIM_inv.py --input_image images/chair1.jpg --results_folder ./output/rev_brown_chair_yes_threshold_segmented && python _3_dpl_seg_inv.py --input_image images/chair1.jpg --results_folder output/rev_brown_chair_yes_threshold_segmented --initializer_token one two three four five six --placeholder_token  '<one>' '<two>' '<three>' '<four>' '<five>' '<six>' --smooth_op --softmax_op --seg_dirs seg_dirs/rendered_chair --exp_name rev_brown_chair_yes_threshold_segmented --beta_cos 0.2 --beta_iou 0.2 --beta_kl 0.2 --beta_sim 0.2 --beta_adj 0.0


python _2_DDIM_inv.py --input_image images/chair1.jpg --results_folder ./output/rev_brown_chair_yes_threshold_with_ours && python _3_dpl_seg_inv.py --input_image images/chair1.jpg --results_folder output/rev_brown_chair_yes_threshold_with_ours --initializer_token chair --placeholder_token  '<chair>' --smooth_op --softmax_op --seg_dirs seg_dirs/rendered_chair --exp_name rev_brown_chair_yes_threshold_with_ours 


python _2_DDIM_inv.py --input_image images/rendered_stool.jpg --results_folder ./output/rev_brown_chair_onto_stool && python _3_dpl_seg_inv.py --input_image images/rendered_stool.jpg --results_folder output/rev_brown_chair_onto_stool --initializer_token chair --placeholder_token  '<chair>' --smooth_op --softmax_op --seg_dirs seg_dirs/rendered_stool --exp_name rev_brown_chair_onto_stool --input_embs_path output/rev_brown_chair_yes_threshold/embed_list/rev_brown_chair_yes_threshold-cos_al_50.0_beta_0.7_lam_1.0_iou_al_25.0_beta_0.7_lam_1.0_kl_al_25.0_beta_1.0_lam_1.0_adj_al_50.0_beta_0.1_lam_2.0_softmax_True_smooth_True_null_31_attn_31_CFG_7.5_adj_False/chair1 && python _3_dpl_seg_inv.py --input_image images/rendered_stool.jpg --results_folder output/rev_brown_chair_onto_stool --initializer_token chair --placeholder_token  '<chair>' --smooth_op --softmax_op --seg_dirs seg_dirs/rendered_stool --exp_name rev_brown_chair_onto_stool --input_embs_path output/rev_brown_chair_yes_threshold/embed_list/rev_brown_chair_yes_threshold-cos_al_50.0_beta_0.7_lam_1.0_iou_al_25.0_beta_0.7_lam_1.0_kl_al_25.0_beta_1.0_lam_1.0_adj_al_50.0_beta_0.1_lam_2.0_softmax_True_smooth_True_null_31_attn_31_CFG_7.5_adj_False/chair1  --beta_cos 0.0 --beta_iou 0.0 --beta_kl 0.0 --beta_sim 0.0 --beta_adj 0.0

python _2_DDIM_inv.py --input_image images/rendered_table.jpg --results_folder ./output/rev_brown_chair_back_onto_table && python _3_dpl_seg_inv.py --input_image images/rendered_table.jpg --results_folder output/rev_brown_chair_back_onto_table --initializer_token chair --placeholder_token  '<two>' --smooth_op --softmax_op --seg_dirs seg_dirs/rendered_table --exp_name rev_brown_chair_back_onto_table --input_embs_path output/rev_brown_chair_yes_threshold_segmented/embed_list/rev_brown_chair_yes_threshold_segmented-cos_al_50.0_beta_0.7_lam_1.0_iou_al_25.0_beta_0.7_lam_1.0_kl_al_25.0_beta_1.0_lam_1.0_adj_al_50.0_beta_0.1_lam_2.0_softmax_True_smooth_True_null_31_attn_31_CFG_7.5_adj_False/chair1 && python _3_dpl_seg_inv.py --input_image images/rendered_table.jpg --results_folder output/rev_brown_chair_back_onto_table --initializer_token chair --placeholder_token  '<two>' --smooth_op --softmax_op --seg_dirs seg_dirs/rendered_table --exp_name rev_brown_chair_back_onto_table --input_embs_path output/rev_brown_chair_yes_threshold_segmented/embed_list/rev_brown_chair_yes_threshold_segmented-cos_al_50.0_beta_0.7_lam_1.0_iou_al_25.0_beta_0.7_lam_1.0_kl_al_25.0_beta_1.0_lam_1.0_adj_al_50.0_beta_0.1_lam_2.0_softmax_True_smooth_True_null_31_attn_31_CFG_7.5_adj_False/chair1  --beta_cos 0.0 --beta_iou 0.0 --beta_kl 0.0 --beta_sim 0.0 --beta_adj 0.0

python _2_DDIM_inv.py --input_image images/rendered_stool.jpg --results_folder ./output/rev_brown_chair_back_onto_stool && python _3_dpl_seg_inv.py --input_image images/rendered_stool.jpg --results_folder output/rev_brown_chair_back_onto_stool --initializer_token chair --placeholder_token  '<two>' --smooth_op --softmax_op --seg_dirs seg_dirs/rendered_stool --exp_name rev_brown_chair_back_onto_stool --input_embs_path output/rev_brown_chair_yes_threshold_segmented/embed_list/rev_brown_chair_yes_threshold_segmented-cos_al_50.0_beta_0.7_lam_1.0_iou_al_25.0_beta_0.7_lam_1.0_kl_al_25.0_beta_1.0_lam_1.0_adj_al_50.0_beta_0.1_lam_2.0_softmax_True_smooth_True_null_31_attn_31_CFG_7.5_adj_False/chair1 && python _3_dpl_seg_inv.py --input_image images/rendered_stool.jpg --results_folder output/rev_brown_chair_back_onto_stool --initializer_token chair --placeholder_token  '<two>' --smooth_op --softmax_op --seg_dirs seg_dirs/rendered_stool --exp_name rev_brown_chair_back_onto_stool --input_embs_path output/rev_brown_chair_yes_threshold_segmented/embed_list/rev_brown_chair_yes_threshold_segmented-cos_al_50.0_beta_0.7_lam_1.0_iou_al_25.0_beta_0.7_lam_1.0_kl_al_25.0_beta_1.0_lam_1.0_adj_al_50.0_beta_0.1_lam_2.0_softmax_True_smooth_True_null_31_attn_31_CFG_7.5_adj_False/chair1  --beta_cos 0.0 --beta_iou 0.0 --beta_kl 0.0 --beta_sim 0.0 --beta_adj 0.0

python _3_dpl_seg_inv.py --input_image images/rendered_stool.jpg --results_folder output/rev_brown_chair_back_onto_stool --initializer_token chair --placeholder_token  '<two>' --smooth_op --softmax_op --seg_dirs seg_dirs/rendered_stool --exp_name rev_brown_chair_back_onto_stool --input_embs_path output/rev_brown_chair_yes_threshold_segmented/embed_list/rev_brown_chair_yes_threshold_segmented-cos_al_50.0_beta_0.7_lam_1.0_iou_al_25.0_beta_0.7_lam_1.0_kl_al_25.0_beta_1.0_lam_1.0_adj_al_50.0_beta_0.1_lam_2.0_softmax_True_smooth_True_null_31_attn_31_CFG_7.5_adj_False/chair1


python _3_dpl_seg_inv.py --input_image images/chair1.jpg --results_folder output/rev_brown_chair_yes_threshold --initializer_token chair --placeholder_token  '<chair>' --smooth_op --softmax_op --seg_dirs seg_dirs/rendered_chair --exp_name insert_using_uncond --input_embs_path output/rev_brown_chair_yes_threshold/embed_list/rev_brown_chair_yes_threshold-cos_al_50.0_beta_0.7_lam_1.0_iou_al_25.0_beta_0.7_lam_1.0_kl_al_25.0_beta_1.0_lam_1.0_adj_al_50.0_beta_0.1_lam_2.0_softmax_True_smooth_True_null_31_attn_31_CFG_7.5_adj_False/chair1